version: "3.2"

services:
  postgres:
    image: debezium/postgres:14
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=emr
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: unless-stopped
    #  - ./postgres.conf:/etc/postgresql/postgresql.conf
    #  - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
    # command: postgres -c config_file=/etc/postgresql/postgresql.conf

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped

  orthanc:
    image: jodogne/orthanc-plugins:latest
    hostname: orthanc
    command: /run/secrets/
    volumes:
      # Config
      - ./config/orthanc.json:/etc/orthanc/orthanc.json:ro
      # Persist data
      - ./volumes/orthanc-db/:/var/lib/orthanc/db/
      - ./WorklistsDatabase:/WorklistsDatabase
    ports:
      - '4242:4242' # DICOM
      - '8042:8042' # Web
    secrets:
      - orthanc.json
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
    restart: unless-stopped

  ohif:
    build: 
      context: ../../apps/ohif/
      dockerfile: ./platform/viewer/.recipes/OpenResty-Orthanc/dockerfile
    image: ohif:latest
    container_name: ohif 
    volumes:
      # Nginx config
      - ./config/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
      # Logs
      - ./logs/nginx:/var/logs/nginx
      # Let's Encrypt
      # - letsencrypt_certificates:/etc/letsencrypt
      # - letsencrypt_challenges:/var/www/letsencrypt
    ports:
      - '443:443' # SSL
      - '80:80' # Web
    depends_on:
      - orthanc
    restart: on-failure

volumes:
  postgres:

secrets:
  orthanc.json:
    file: ./config/orthanc.json
