export const FHIR_URL = process.env.NX_PUBLIC_FHIR_URL;
export const APP_SERVER_URL = process.env.NX_PUBLIC_APP_SERVER_URL;

export * from './appointment';
export * from './organization';
export * from './value_set';
export * from './user'
export * from './schedule';
export * from './slot';
export * from './patient';
export * from './code_system';
export * from './extensions';
export * from './location';
export * from './encounter';
export * from './activity_definition';
export * from './task';
export * from './snomed';
export * from './util';
export * from './condition';
export * from './procedure';
export * from './immunization';
export * from './allergyintolerance';
export * from './rxnorm';
export * from './medication';
export * from './medication_statement';
export * from './templates';
export * from './questionnaire';
export * from './observation';
export * from './questionnaire_response';
export * from './care_team';